routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('admin');
});
Route::get('home', function () {
    return redirect('admin');
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
    'confirm' => false,
]);

//Route::get('/home', 'HomeController@index')->name('home');
Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::group(['as' => 'vacancies.'], function () {
        Route::get('/', 'VacancyController@index')->name('list');
        Route::get('/edit/{id?}', 'VacancyController@edit')->name('edit');
        Route::post('/store/{id?}', 'VacancyController@store')->name('store');
        Route::post('/vacancytitle', 'VacancyController@vacancyChangeTitle')->name('title');
    });
    Route::group(['as' => 'applicants.'], function () {
        Route::get('/applicants', 'ApplicantController@index')->name('list');
    });
});

app/Applicant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Applicant extends Model
{
    protected $fillable = ['name','phone','email','description'];

    public function vacancies()
    {
        return $this->hasMany(ApplicantVacancy::class);
    }
}

app/ApplicantStatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ApplicantStatus extends Model
{
    //
}

app/ApplicantVacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ApplicantVacancy extends Model
{
    protected $fillable = ['applicant_id','vacancy_id','status_id','file'];

    public function applicant()
    {
        return $this->belongsTo(Applicant::class);
    }

    public function vacancy()
    {
        return $this->belongsTo(Vacancy::class);
    }

    public function status()
    {
        return $this->belongsTo(ApplicantStatus::class);
    }
}

app/Interview.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Interview extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Vacancy.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vacancy extends Model
{
    protected $fillable = ['title','description','status_id'];
    const INIT_STATUS = 'Open';

    public function status()
    {
        return $this->belongsTo(VacancyStatus::class);
    }
    public function applicants()
    {
        return $this->belongsToMany(Applicant::class,'vacancies','id','applicant_id','zipcode_id');
    }

    public function scopeActive($query)
    {
        return $query->whereHas('status', function ($qStatus){
            $qStatus->whereName(self::INIT_STATUS);
        });
    }

}

app/VacancyStatus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class VacancyStatus extends Model
{
    //
}

app/Http/Controllers/Api/ApplicantController.php
<?php


namespace App\Http\Controllers\Api;

use App\Applicant;
use App\ApplicantVacancy;
use App\Vacancy;
use App\VacancyStatus;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ApplicantController extends Controller
{
    public function getAllApplicants(Request $request)
    {
        $appList = ApplicantVacancy::with('applicant','vacancy')->get();
        //todo pagination

        return response()->json($appList);
    }

    public function applyToVacancy($vacancyId, Request $request)
    {
        //todo validate request
        $applicant = Applicant::updateOrCreate([
            'name'=>$request->name,
            'email'=>$request->email,
            'phone'=>$request->phone,
            ],[
                'description'=>$request->description,
        ]);
        //todo file upload
        $status = VacancyStatus::whereName(Vacancy::INIT_STATUS)->first();
        if($status){
            ApplicantVacancy::create([
                'applicant_id'=>$applicant->id,
                'vacancy_id'=>$vacancyId,
                'file'=>$request->file,
                'status_id'=>$status->id,
            ]);
        }

        return response('Ok');
    }
}

app/Http/Controllers/Api/VacancyController.php
<?php


namespace App\Http\Controllers\Api;


use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Vacancy;


class VacancyController extends Controller
{
    public function getActiveVacancies(Request $request)
    {
        $vacancies = Vacancy::active()->get();
        //todo pagination
        return response()->json($vacancies);
    }
}

app/Http/Controllers/ApplicantController.php
<?php

namespace App\Http\Controllers;

use App\Applicant;
use App\ApplicantVacancy;
use Illuminate\Http\Request;

class ApplicantController extends Controller
{
    const APPLICANT_PER_PAGE = 15;

    public function index(Request $request)
    {
        $applicants = ApplicantVacancy::with('applicant','vacancy')
            ->latest()->paginate(self::APPLICANT_PER_PAGE);

        return view('applicant.applicantlist',compact('applicants'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/InterviewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class InterviewController extends Controller
{
    //
}

app/Http/Controllers/VacancyController.php
<?php

namespace App\Http\Controllers;

use App\{Vacancy, VacancyStatus};
use App\Http\Requests\VacancyFormRequest;
use Illuminate\Http\Request;

class VacancyController extends Controller
{
    const VACANCIES_PER_PAGE = 15;

    public function index(Request $request)
    {
        $vacancies = Vacancy::with('status')->latest()->paginate(self::VACANCIES_PER_PAGE);

        return view('vacancy.vacancy',compact('vacancies'));
    }

    public function edit($vacancyId=0)
    {
        $vacancy = null;

        $statuses = VacancyStatus::pluck('name','id');
        if(empty($vacancyId)){
            $vacancy = new Vacancy();
            $vacancy->status_id = $statuses->search(Vacancy::INIT_STATUS);
        }else {
            $vacancy = Vacancy::findOrFail($vacancyId);
        }

        return view('vacancy.vacancy_form',compact('vacancy','statuses'));
    }

    public function store(VacancyFormRequest $request,$vacancyId=0)
    {
        if(empty($vacancyId)){
            Vacancy::create($request->all());
        }else{
            Vacancy::findOrFail($vacancyId)->update($request->all());
        }

        return redirect()->route('vacancies.list')->withMessage('Vacancy was successful added.');
    }
    public function vacancyChangeTitle(Request $request)
    {
        if(empty($request->id) || empty($request->title)){
            return response("Id or Title not found", 201);
        }
        Vacancy::findOrFail($request->id)->update(
            ['title'=>$request->title]
        );

        return response("Ok", 200);
    }
}

resources/views/applicant/applicantlist.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('layouts.messages_from_session')
        </div>
        <div class="row justify-content-center shadow-sm sticky-top font-weight-bold mt-2">
            <div class="col-md-2">Date</div>
            <div class="col-md-2">Name</div>
            <div class="col-md-2">Phone</div>
            <div class="col-md-2">Email</div>
            <div class="col-md-2">Vacancy</div>
            <div class="col-md-1">Status</div>
            <div class="col-md-1">File</div>
        </div>
        @foreach($applicants as $applicant)
            <div class="row justify-content-center mt-1">
                <div class="col-md-2">{{$applicant->created_at->format('d-m-Y')}}</div>
                <div class="col-md-2">{{$applicant->applicant->name}}</div>
                <div class="col-md-2">{{$applicant->applicant->phone}}</div>
                <div class="col-md-2">{{$applicant->applicant->email}}</div>
                <div class="col-md-2">{{$applicant->vacancy->title}}</div>
                <div class="col-md-1">{{$applicant->status->name}}</div>
                <div class="col-md-1">{{$applicant->file}}</div>
            </div>
        @endforeach
        <div class="row justify-content-center">
            {{$applicants->links()}}
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
{{--                <a class="navbar-brand" href="{{ url('/') }}">--}}
{{--                    {{ config('app.name', 'Laravel') }}--}}
{{--                </a>--}}
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @include('layouts.main_menu')
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/main_menu.blade.php
<ul class="navbar-nav mr-auto">
    <li class="mr-3 {{Route::currentRouteName()=='vacancies.list'?'font-weight-bold':''}}">
        <a href="{{route('vacancies.list')}}">Vacancy list</a>
    </li>
    <li class="mr-3 {{Route::currentRouteName()=='applicants.list'?'font-weight-bold':''}}">
        <a href="{{route('applicants.list')}}">Applicants list</a>
    </li>
</ul>

resources/views/layouts/messages_from_session.blade.php
@if(session('message'))
    <div class="alert alert-success"> {{session('message')}}</div>
@endif
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/singlepage/main.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Vacancies list') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app">
    <!-- Scripts -->
    <script src="{{ asset('js/singleapp.js') }}" defer></script>
</div>
</body>
</html>

resources/views/vacancy/vacancy.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            @include('layouts.messages_from_session')
        </div>
        <div class="row mt-2">
            <div class="col-md-5"><a class="btn btn-primary" href="{{route('vacancies.edit')}}">Add vacancy</a></div>
        </div>
        <div class="row justify-content-center shadow-sm sticky-top font-weight-bold mt-2">
            <div class="col-md-2">Date</div>
            <div class="col-md-3">Title</div>
            <div class="col-md-5">Description</div>
            <div class="col-md-1">Status</div>
            <div class="col-md-1">Actions</div>
        </div>
        @foreach($vacancies as $vacancy)
        <div class="row justify-content-center mt-1">
            <div class="col-md-2">{{$vacancy->created_at->format('d-m-Y')}}</div>
            <div class="col-md-3">
                <input-saver value="{{$vacancy->title}}" url='{{route('vacancies.title')}}' id="{{$vacancy->id}}" field="title"></input-saver>
            </div>
            <div class="col-md-5">{{$vacancy->description}}</div>
            <div class="col-md-1">{{optional($vacancy->status)->name}}</div>
            <div class="col-md-1">
                <a class="btn btn-primary" href="{{route('vacancies.edit',$vacancy->id)}}">Edit</a>
            </div>
        </div>
        @endforeach
        <div class="row justify-content-center">
            {{$vacancies->links()}}
        </div>
    </div>
@endsection

resources/views/vacancy/vacancy_form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h3>Vacancy editor</h3>
        @include('layouts.messages_from_session')
        <form action="{{route('vacancies.store',$vacancy->id)}}" method="post">
            @csrf
            <div class="col-md-12">
                <label for="name">Title *</label>
                <input name="title" value="{{$vacancy->title}}" required class="form-control">
            </div>
            <div class="col-md-12">
                <label for="name">Description *</label>
                <textarea name="description" required class="form-control">{{$vacancy->description}}</textarea>
            </div>
            <div class="col-md-12">
                <label for="name">Status *</label>
                <select name="status_id" required class="form-control">
                    @foreach($statuses as $key=>$status)
                    <option value="{{$key}}" {{$key==$vacancy->status_id?'selected':''}}>{{$status}}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-md-12 mt-2">
                <button class="btn btn-primary" type="submit">{{empty($vacancy->id)?'Create vacancy':'Save vacancy'}}</button>
                <a class="btn btn-secondary" href="{{route('vacancies.list')}}">Back</a>
            </div>
        </form>
    </div>
@endsection